### ISSUE TITLE
Multi-language

### ISSUE THREAD

**Issue by SrPatinhas** [DJScias/LoLES#10]
- Portuguese
- English
- ?

**Comment by DJScias** [comment]
I guess we can do this, let me see what I can brew up for English and Dutch.

**Comment by SrPatinhas** [comment]
then
- [x] English
- [ ] Portuguese
- [ ] Dutch
- [ ] Frances
- [ ] Germany
- [ ] Mandarin?

**Comment by DJScias** [comment]
Found a way to do this, this is what I've done.
- [x] used chrome's i18n support for Extension title & Description
- [x] created custom i18n support through JQuery functions
- [x] replaced all strings with i18n strings
- [x] added full messages.json for English (this one can be used as basis for other languages)

**Comment by DJScias** [comment]
Implemented with 347824cd395c5387b8042df58b3aaf5eb2fab8b0
